# Generated by Django 3.1.7 on 2021-05-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
