# Generated by Django 3.1.7 on 2021-06-05 12:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_billing_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingadress',
            name='countries',
        ),
        migrations.AddField(
            model_name='billingadress',
            name='country',
            field=django_countries.fields.CountryField(default='China', max_length=2),
            preserve_default=False,
        ),
    ]
